filter feed reblogs
ecency/ecency-vision pull request #1002
Opened 2022-08-16 15:16 UTC by Adesojisouljay

2022-08-23 04:17 UTC, feruzm requested changes

2022-08-23 04:17 UTC, feruzm commented on src/common/pages/entry-index.tsx
> +        console.log('componentDidMount');
No need this log

2022-08-23 04:17 UTC, feruzm commented on src/common/components/entry-index-menu-dropdown/index.tsx
> +        {tag === "" ? _t('entry-filter.filter-global') : tag === 'my' ? _t('entry-filter.filter-community') : tag === 'today' ? _t('entry-filter.filter-today') : tag === 'week' ? _t('entry-filter.fil
There is some logical issue here: For example, if I am logged in with @demo but want to see other user's feed (@ecency's feed) /@ecency/feed then I get in options `@ecency` and `Exclude reblogs`. Also looks like when logout we are not showing feed of any user, this is bug, maybe we can fix that here as well. Find out why it is not rendering/recognizing.

2022-08-23 06:09 UTC, Adesojisouljay commented
This is noted, I will check and fix bug.

Thanks.

On Tue, 23 Aug 2022, 5:18 am Feruz M, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/common/pages/entry-index.tsx
> <https://github.com/ecency/ecency-vision/pull/1002#discussion_r952132822>:
>
> >      };
>
>      componentDidMount() {
> +        console.log('componentDidMount');
>
> No need this log
> ------------------------------
>
> In src/common/components/entry-index-menu-dropdown/index.tsx
> <https://github.com/ecency/ecency-vision/pull/1002#discussion_r952134155>:
>
> >    const dropDownConfig = {
>      history: null,
>      label: (
>        <div className='tagDropDown'>
>          <span className='pl-2' />
> -        {tag === "" ? _t('entry-filter.filter-global') : tag === 'my' ? _t('entry-filter.filter-community') : tag === 'today' ? _t('entry-filter.filter-today') : tag === 'week' ? _t('entry-filter.filter-week') : tag === 'month' ? _t('entry-filter.filter-month'): tag === 'year' ? _t('entry-filter.filter-year') : tag === 'all' ? _t('entry-filter.filter-alltime') : tag}
> +        {tag === "" ? _t('entry-filter.filter-global') : tag === 'my' ? _t('entry-filter.filter-community') : tag === 'today' ? _t('entry-filter.filter-today') : tag === 'week' ? _t('entry-filter.filter-week') : tag === 'month' ? _t('entry-filter.filter-month'): tag === 'year' ? _t('entry-filter.filter-year') : tag === 'all' ? _t('entry-filter.filter-alltime') : tag === `@${activeUser.username}` ? (props.noReblog === true ? _t('entry-filter.filter-no-reblog') : _t('entry-filter.filter-with-reblog')) : tag}
>
> There is some logical issue here: For example, if I am logged in with
> @demo <https://github.com/demo> but want to see other user's feed ***@***.***
> <https://github.com/ecency>'s feed) ***@***.***/feed then I get in options
> @ecency and Exclude reblogs. Also looks like when logout we are not
> showing feed of any user, this is bug, maybe we can fix that here as well.
> Find out why it is not rendering/recognizing.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ecency/ecency-vision/pull/1002#pullrequestreview-1081439217>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVAB2UVM7S6F2Q6CCFHY2FTV2RGIBANCNFSM56WHTGQQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-08-27 06:42 UTC, closed without merging

2022-08-27 06:49 UTC, Adesojisouljay commented
Issue has been resolved on a new branch.