voting slider issue
ecency/ecency-vision pull request #1090
Opened 2022-11-01 10:43 UTC by MTSaeed

**What does this PR?**
voting slider range should has a difference of 5%.

**Steps to reproduce**
open any post and try to vote that post.
observe that the difference of voting slider should be 5.

**Issue number**
fixes #[1083](https://github.com/ecency/ecency-vision/issues/1083)

**Screenshots/Video**

https://user-images.githubusercontent.com/106739598/199215883-6d88cbee-6dcc-4967-b6d4-bd0e2d742580.mp4

2022-11-02 12:09 UTC, feruzm commented
@MTSaeed This seem to lock you in 5% range always, idea is to allow in between also but also easier to select values, someone suggested visual separator every 5 or 10% but allow easy scrolling in between as well. Is it possible?

2022-11-14 09:20 UTC, MTSaeed commented
@feruzm kindly check this.

https://user-images.githubusercontent.com/106739598/201622131-4b7f2f0a-395b-4f8d-94ad-5cca266b0b76.mp4

2022-11-14 10:06 UTC, feruzm commented
@MTSaeed much better, can we make it like this, meaning have small dot separators inside slider and on desktop show 10 points (0 10 20 30 40 ... 90 100) but on mobile view show 5 points (0 25 50 75 100).

and we can slightly increase length of slider so numbers won't collide to each other, see last screenshot.

<img width="213" alt="Screenshot 2022-11-14 at 15 31 07" src="https://user-images.githubusercontent.com/3015990/201631581-8f7046c7-ccae-4961-bcc8-045b60b8bcc8.png">

<img width="465" alt="Screenshot 2022-11-14 at 15 34 31" src="https://user-images.githubusercontent.com/3015990/201632303-ca5f216b-9d72-4b34-815d-7ce73273c00a.png">

![image](https://user-images.githubusercontent.com/3015990/201632660-c089192d-6e93-4431-9c9b-49f208fbcf06.png)

2022-11-22 08:19 UTC, MTSaeed commented
Loom video link

https://www.loom.com/share/fb82632df2a54927b03844c0478a90a1

2022-11-22 14:24 UTC, feruzm requested changes

2022-11-22 14:24 UTC, feruzm commented on src/common/components/entry-vote-btn/_index.scss
> +.line-slider{
@MTSaeed As we discussed in our call, there are couple issues still remaining, here in this picture I clicked 75 but got this...
![image](https://user-images.githubusercontent.com/3015990/203338227-fbbd5291-535b-4a3f-8513-48907be1a7ce.png)

2022-11-24 14:51 UTC, feruzm approved these changes
lgtm

2022-11-24 14:51 UTC, merged