hive engine chart
ecency/ecency-vision pull request #1097
Opened 2022-11-07 17:45 UTC by Adesojisouljay

2022-11-09 13:50 UTC, feruzm commented
@Adesojisouljay What token chart is being displayed? Idea with this feature was slightly different.

1. No need new chart library, we already have highcharts integrated, please utilize that.
2. Idea was to have chart about each token just like Ecency mobile wallet page. Here I tried to make quick sketch: 
![image](https://user-images.githubusercontent.com/3015990/200846759-4bc09f7c-203b-4243-a8c9-8586875d2210.png)
Use space between token label and balance and display chart/price info as background and on mobile browsers, we don't need to show charts.
3. For tokens that doesn't have market history or chart data, then show straight line basically. (non changing price)

2022-11-09 14:01 UTC, Adesojisouljay commented
I haven't pushed some commits, that's was a sample in first commits.

I will check previous library.

On Wed, 9 Nov 2022, 2:50 pm Feruz M, ***@***.***> wrote:

> @Adesojisouljay <https://github.com/Adesojisouljay> What token chart is
> being displayed? Idea with this feature was slightly different.
>
>    1. No need new chart library, we already have highcharts integrated,
>    please utilize that.
>    2. Idea was to have chart about each token just like Ecency mobile
>    wallet page. Here I tried to make quick sketch:
>    [image: image]
>    <https://user-images.githubusercontent.com/3015990/200846759-4bc09f7c-203b-4243-a8c9-8586875d2210.png>
>    Use space between token label and balance and display chart/price info
>    as background and on mobile browsers, we don't need to show charts.
>    3. For tokens that doesn't have market history or chart data, then
>    show straight line basically. (non changing price)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ecency/ecency-vision/pull/1097#issuecomment-1308795576>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVAB2UXIFK2Q7RSPEFJYEZLWHOT2NANCNFSM6AAAAAARZODDMU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-11-23 10:07 UTC, feruzm requested changes

2022-11-23 10:07 UTC, feruzm commented on package.json
> +    "chart.js": "^3.9.1",
chart.js is still being added, couldn't we use highcharts for this? @Adesojisouljay

2022-11-23 10:07 UTC, feruzm commented on src/common/components/hive-engine-chart/index.tsx
> +          `https://info-api.tribaldex.com/market/ohlcv`,
Can we set all hive-engine servers inside servers.json or create he-servers.json inside constants folder? So we don't hard code all separately but from single place when issue occurs we can replace from single place, not from all random components.

2022-11-24 10:24 UTC, feruzm approved these changes
lgtm, HIVE_ENGINE_RPC_URL and chartApi should be under one file perhaps in separate PR.

2022-11-24 10:24 UTC, merged

2022-11-24 10:30 UTC, Adesojisouljay commented
Yes, will move that shortly

On Thu, 24 Nov 2022, 11:24 am Feruz M, ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> lgtm, HIVE_ENGINE_RPC_URL and chartApi should be under one file perhaps in
> separate PR.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ecency/ecency-vision/pull/1097#pullrequestreview-1192912657>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVAB2USQJSELCV7GNWKLMD3WJ467FANCNFSM6AAAAAARZODDMU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>