Editor shortcuts
ecency/ecency-vision pull request #1151
Opened 2022-12-08 07:58 UTC by MTSaeed

**What does this PR?**

Create shortcuts of keyboard while creating the post.
Shortcuts for different functionalities are given below:
Bold = ctrl + b
Italic = ctrl + i
To make new table = alt + t
To create a link = alt + k
For code block = alt + c
To upload an image = alt +d
To add blockquote = ctrl + m
 
**Steps to reproduce**

1. Open the create post page.
2. white some text and apply the shortcuts.

**Issue number** 

fixes #[1104](https://github.com/ecency/ecency-vision/issues/1104

**Screenshot/Video**

https://user-images.githubusercontent.com/106739598/206391200-d6c5a818-77b8-4f9c-b3eb-5bff22f27f34.mp4

2022-12-10 04:57 UTC, feruzm requested changes
Can we stick with either Ctrl or Alt combination? I would prefer Alt, also on hover on those icons in editor toolbar, we should show tooltip about these shortcuts, so people can learn/see there is shortcut option.

2022-12-13 07:50 UTC, MTSaeed commented
> Can we stick with either Ctrl or Alt combination? I would prefer Alt, also on hover on those icons in editor toolbar, we should show tooltip about these shortcuts, so people can learn/see there is shortcut option.

We could use alt in all. But it is more intuitive to use ctrl + b and ctrl + i for bold and italic as these shortcuts have become vast practices. What is your opinion about this?

2022-12-13 09:36 UTC, feruzm commented
@MTSaeed We shouldn't forget OS and Browser shortcuts, people might want to keep those keys. Let's do Alt and gather community feedback, if we get more requests to change it to Ctrl, we can do so easily.

2022-12-13 13:21 UTC, dkildar commented on src/common/pages/submit.tsx
> +  shortcuts = (e: any) => {
Second one: functions names should describe an action. In this case: `handleShortcuts`

2022-12-13 14:10 UTC, MTSaeed commented on src/common/pages/submit.tsx
> +  shortcuts = (e: any) => {
Updated.

2022-12-15 02:17 UTC, feruzm approved these changes
lgtm

2022-12-15 02:17 UTC, merged