Fix no show topics
ecency/ecency-vision pull request #758
Opened 2021-12-25 08:12 UTC by mghazanfar

2021-12-25 08:41 UTC, feruzm requested changes
@mghazanfar It does fetch topics always unnecessarily. I think we should improve a logic bit further. For example for community feeds we don’t need topics because we don’t show them there. Maybe cache or keep topics in redux for an hour or until hare refresh so we don’t fetch them every time?!

2021-12-25 08:43 UTC, mghazanfar commented
> @mghazanfar It does fetch topics always unnecessarily. I think we should improve a logic bit further. For example for community feeds we don’t need topics because we don’t show them there. Maybe cache or keep topics in redux for an hour or until hare refresh so we don’t fetch them every time?!

Sure.

2021-12-30 16:20 UTC, ghazanfar-BrilliantStar commented
> @mghazanfar It does fetch topics always unnecessarily. I think we should improve a logic bit further. For example for community feeds we don’t need topics because we don’t show them there. Maybe cache or keep topics in redux for an hour or until hare refresh so we don’t fetch them every time?!

@feruzm I just went into details. Added my logic as well. But when I saw ``/ecency-vision/src/common/store/trending-tags/index.ts`` the logic is already there. If trending tags are already there then it does not refetch and recalls the API so I think we're good to go. It is already optimized.

2021-12-30 17:15 UTC, feruzm approved these changes

2021-12-30 17:16 UTC, merged